# language: node_js
# addons:
#   chrome: stable
# cache:
#   directories:
#     - "Tassel.angular4/node_modules"
# node_js:
#   - "8"
# before_install:
#     - "cd Tassel.angular4"
#     - "npm install"

language: node_js
node_js:
  - "8"
branches:
  only:
    - master
before_script:
  - npm install
script:
  - npm run build:prod