// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Tassel.DomainModel.Models;

namespace Tassel.Model.Migrations
{
    [DbContext(typeof(APIDB))]
    [Migration("20170923072156_newMigra")]
    partial class newMigra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tassel.DomainModel.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnName("desc");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Tassel.DomainModel.Models.User", b =>
                {
                    b.Property<string>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("c_time");

                    b.Property<string>("Email")
                        .HasColumnName("email");

                    b.Property<string>("FamilyName")
                        .HasColumnName("f_name");

                    b.Property<int?>("Gender")
                        .HasColumnName("gender");

                    b.Property<string>("GivenName")
                        .HasColumnName("g_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("psd");

                    b.Property<string>("QQToken")
                        .HasColumnName("qq_token");

                    b.Property<int>("RoleID")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnName("u_time");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("u_name");

                    b.Property<string>("WechatToken")
                        .HasColumnName("wechat_token");

                    b.Property<string>("WeiboToken")
                        .HasColumnName("weibo_token");

                    b.HasKey("UUID");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
